%%
%% An attempt to do plasma line tracing with code generated by gemini AI
%% The traces tracked with this could be used as initial values for gaussian fits to the ACF data. 
%%
%%
%% OR should we somehow include the fit in this process? (fit altitudes one-by-one inside the loops below)
%%
%% IV 2026
%%

%
%
% From the discussion with Google gemini
% The Dynamic Programming ApproachThis method is often called Seam Carving logic or the Viterbi Algorithm in signal processing. You build a "cost matrix" that accumulates the best possible path to every pixel.1. Define Your CostEach pixel \((x, y)\) has a cost. For a bright curve on a dark background, use \(Cost = 255 - Intensity\).Goal: Find a path from \(x=0\) to \(x=Width\) that minimizes the total sum of costs.2. Apply the Monotonic ConstraintIn your DP update step, you only allow "upward" or "forward" moves. If moving left-to-right, a pixel at \((x, y)\) can only have come from:\((x-1, y)\) — stayed at same height.\((x-1, y-1)\) — moved up one pixel.(Optional) \((x-1, y-2)\) — if you allow steeper slopes.3. The Update RuleFor every pixel, calculate the cumulative cost \(S(x, y)\):\(S(x,y)=Cost(x,y)+\min (S(x-1,y),S(x-1,y-1))\)
    
% more notes...
% To ensure you are truly finding the "global" best path from edge-to-seed, check these three things in your code:Cumulative Summation: Inside your loops, you must have S(r, c) = Cost(r, c) + minVal;. This ensures every pixel "inherits" the total history of the path before it.Edge Selection: By picking the min of the entire row S(1, :) (top) or S(rows, :) (bottom), you are testing every possible entry point on that edge.The "Infinity" Trap: Ensure you initialized S with inf. This ensures that any pixel that cannot be reached from the seed (based on your max_jump constraint) is never chosen as a starting point for backtracking.


function [curve_cols, seedR] = plfind_geminiAI(r_spec,plotres)

% Convert to double and handle negative values
data = double(r_spec');
%data = data - min(data(:)); % Shift to 0-max range
data  = data - quantile(data(:),.2);
data(data<0) = 0;
data = data / quantile(data(:),.95);max(data(:)); % Optional: Scale 0 to 1 for easier penalty tuning
data(data>1) = 1;

% 1. Pre-process: Robust Seed Selection
% We use a 2D blur just to find the "Anchor", then 1D blur for pathfinding
anchor_blur = imfilter(double(data), fspecial('gaussian', 10, 2)); 
[~, maxIdx] = max(anchor_blur(:));
[seedR, seedC] = ind2sub(size(data), maxIdx);

% 2. Horizontal Blur for Pathfinding (as requested)
sigma_h = 7; 
data_smoothed = imfilter(double(data), fspecial('gaussian', [1, 30], sigma_h), 'replicate');

[rows, cols] = size(data);
%Cost = -data_smoothed; % Minimize negative intensity
Cost = log(1 + (1-data_smoothed));
S = inf(rows, cols);
Parent = zeros(rows, cols);

% Penalize large horizontal jumps to bridge gaps smoothly
jump_penalty = 1e-3; % Increase to make curve "straighter" across gaps
max_jump = 50;   % Increase if the curve moves very quickly horizontally

% Initialize at the brightest anchor point
S(seedR, seedC) = Cost(seedR, seedC);

% % 3. Bi-Directional DP with "Quick Move" Support
% % --- UPWARD PASS ---
% for r = seedR-1 : -1 : 1
%     for c = 1:cols
%         % Look at a wider window (max_jump) to allow quick horizontal movement
%         c_low = max(1, c - max_jump);
%         c_high = min(cols, c + max_jump);
        
%         % Calculate cost with a penalty for the horizontal distance moved
%         dist = abs((c_low:c_high) - c);
%         [minVal, idx] = min(S(r+1, c_low:c_high) + (dist * jump_penalty));
        
%         S(r, c) = Cost(r, c) + minVal;
%         win_indices = c_low:c_high;
%         Parent(r, c) = win_indices(idx);
%     end
% end
% --- Inside the DP Loop (Example for Upward Pass) ---
% New parameter:
smoothness_weight = 1e-3; % Penalty for changing direction

for r = seedR-1 : -1 : 1
    for c = 1:cols
        c_low = max(1, c - max_jump);
        c_high = min(cols, c + max_jump);
        
        % 1. Horizontal distance penalty (prevents huge jumps)
        dist = abs((c_low:c_high) - c);
        
        % 2. Directional penalty (Inertia)
        % We look at the Parent of the previous step to see the 'heading'
        prev_c = Parent(r+1, c_low:c_high);
        heading = (c_low:c_high) - prev_c; 
        current_move = c - (c_low:c_high);
        direction_change = abs(current_move - heading);
        
        % Calculate total cost
        total_move_cost = (dist * jump_penalty) + (direction_change * smoothness_weight);
        
        [minVal, idx] = min(S(r+1, c_low:c_high) + total_move_cost);
        
        S(r, c) = Cost(r, c) + minVal;
        win_indices = c_low:c_high;
        Parent(r, c) = win_indices(idx);
    end
end

% % --- DOWNWARD PASS ---
% for r = seedR+1 : rows
%     for c = 1:cols
%         c_low = max(1, c - max_jump);
%         c_high = min(cols, c + max_jump);
        
%         dist = abs((c_low:c_high) - c);
%         [minVal, idx] = min(S(r-1, c_low:c_high) + (dist * jump_penalty));
        
%         S(r, c) = Cost(r, c) + minVal;
%         win_indices = c_low:c_high;
%         Parent(r, c) = win_indices(idx);
%     end
% end
% --- DOWNWARD PASS (from seedR+1 to rows) ---
%smoothness_weight = 2e-3; % Penalty for changing direction
for r = seedR+1 : rows
    for c = 1:cols
        % Define the horizontal search window
        c_low = max(1, c - max_jump);
        c_high = min(cols, c + max_jump);
        win_indices = c_low:c_high;
        
        % 1. Horizontal distance penalty (prevents huge jumps)
        dist = abs(win_indices - c);
        
        % 2. Directional penalty (Inertia/Momentum)
        % We look at the Parent of the previous step (r-1) 
        % to see where those pixels came from.
        prev_c_for_window = Parent(r-1, win_indices);
        
        % If we are just starting at the seed, prev_c might be 0. 
        % We handle that by assuming a straight heading (0) for the first step.
        heading = win_indices - prev_c_for_window;
        heading(prev_c_for_window == 0) = 0; 
        
        current_move = c - win_indices;
        direction_change = abs(current_move - heading);
        
        % Total movement cost
        total_move_cost = (dist * jump_penalty) + (direction_change * smoothness_weight);
        
        % Find the best path to reach pixel (r, c)
        [minVal, idx] = min(S(r-1, win_indices) + total_move_cost);
        
        S(r, c) = Cost(r, c) + minVal;
        Parent(r, c) = win_indices(idx);
    end
end


% could test starting from each column and find the minimum sum of costs???


% 4. Backtrack (Ensures full height coverage)
curve_cols = zeros(rows, 1);

% From Top to Seed
[~, currC] = min(S(1, :));
for r = 1 : seedR-1
    curve_cols(r) = currC;
    currC = Parent(r, currC);
end

% From Bottom to Seed
[~, currC] = min(S(rows, :));
for r = rows : -1 : seedR
    curve_cols(r) = currC;
    currC = Parent(r, currC);
end


% % Extract intensity along the path
% path_intensities = zeros(rows, 1);
% for r = 1:rows
%     %    path_intensities(r) = r_spec(round(curve_cols(r)),r);
%     path_intensities(r) = data_smoothed(r,round(curve_cols(r)));
% end
% % Calculate a threshold (e.g., 20% of the max intensity found on this path)
% threshold = 0.02 * max(path_intensities);

% % Create a logical mask of "valid" points
% valid_points = path_intensities > threshold;

% % Filter the curve
% pruned_curve_cols = curve_cols;
% pruned_curve_cols(~valid_points) = NaN; % NaN values won't show up in plots

% Example: Is the point 1.5x brighter than the local average?
% pruned_curve_cols = curve_cols;
% for r = 1:rows
%     %    local_bg = mean(r_spec(r, :)); % Or a local window around curve_cols(r)
%     local_bg = mean(data_smoothed(r, :)); % Or a local window around curve_cols(r)
%     if path_intensities(r) < 1.5 * local_bg
%         pruned_curve_cols(r) = NaN;
%     end
% end

if plotres
    % 5. Visualize
    %imagesc(r_spec'); colormap gray; hold on;
    subplot(1,2,1)
    %pcolor(r_spec'); shading flat;
    %pcolor(anchor_blur); shading flat;
    pcolor(r_spec'); shading flat;
    subplot(1,2,2)
    pcolor(r_spec'); shading flat; hold on
    %pcolor(data_smoothed); shading flat; hold on;
    %pcolor(S); shading flat; hold on;
    %plot(pruned_curve_cols, 1:rows, 'r-', 'LineWidth', 1.5);
    plot(curve_cols, 1:rows, 'r-', 'LineWidth', 1.5);
    plot(seedC, seedR, 'gx', 'MarkerSize', 15, 'LineWidth', 2); % The Seed
    hold off

end

end
